# Generated by Django 5.0.6 on 2024-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommendation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.JSONField(default=list),
        ),
    ]
